resources:
  - https://github.com/hdamarcelo/cos-fleetshard//etc/kubernetes/manifests/overlays/staging/cos-fleetshard-operator-camel/?ref=v1.1.12
images:
  - name: quay.io/rhoas/cos-fleetshard-operator-camel
    digest: ""
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cos-fleetshard-operator-camel
    spec:
      template:
        spec:
          imagePullSecrets:
            - name: addon-pullsecret
